# Generated by Django 3.2 on 2023-06-24 12:45

import django.core.validators
from django.db import migrations, models
import users.validator


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Введите username', max_length=150, unique=True, validators=[users.validator.validate_username, django.core.validators.RegexValidator(code='invalid_field', message='Неправильный формат поляПоле может содержать только буквы,цифры и следующие символы: @ . + -', regex='^[\\w.@+-]+$')], verbose_name='Уникальное имя пользователя'),
        ),
    ]
