# Generated by Django 3.2 on 2023-06-19 11:27

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Введите username', max_length=255, unique=True, validators=[users.models.validate_username], verbose_name='Уникальное имя пользователя'),
        ),
    ]
