# Generated by Django 3.2 on 2023-06-21 06:08

import django.core.validators
from django.db import migrations, models
import users.validator


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_confirmation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Введите username', max_length=150, unique=True, validators=[users.validator.validate_username, django.core.validators.RegexValidator(code='invalid_field', message='Неправильный формат поля', regex='^[\\w.@+-]+$')], verbose_name='Уникальное имя пользователя'),
        ),
    ]
