# Generated by Django 3.2 on 2023-06-21 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20230621_1122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, help_text='Введите имя пользователя', max_length=150, verbose_name='Имя пользователя'),
        ),
    ]
