# Generated by Django 3.2 on 2023-06-14 16:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название категории, это поле обязательное', max_length=256, verbose_name='Название категории')),
                ('slug', models.SlugField(help_text='Это обязательное поле с уникальным значением', unique=True, verbose_name='Слаг категории')),
            ],
        ),
        migrations.CreateModel(
            name='Genres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название жанра, это поле обязательное', max_length=256, verbose_name='Название жанра')),
                ('slug', models.SlugField(help_text='Введите слаг жанра, слаг должен быть уникальным', unique=True, verbose_name='Слаг жанра')),
            ],
        ),
        migrations.CreateModel(
            name='Titles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Введите название произведения, это поле обязательное', max_length=256, verbose_name='Название произведения')),
                ('year', models.IntegerField(verbose_name='Год выхода')),
                ('description', models.TextField(help_text='Введите описания произведения', verbose_name='Описание произведения')),
                ('category', models.OneToOneField(help_text='Введите категорию произведения, поле обязательное', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='reviews.categories', verbose_name='Категория')),
                ('genre', models.OneToOneField(help_text='Введите жанр произведения, поле обязательное', on_delete=django.db.models.deletion.CASCADE, related_name='genres', to='reviews.genres', verbose_name='Жанр')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Введите отзыв, поле обязательное.', null=True, verbose_name='Отзыв')),
                ('score', models.IntegerField(help_text='Рейтинг от 1 до 10', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='Рейтинг')),
                ('pub_date', models.DateField(auto_now=True, verbose_name='Дата')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_authors', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('title_id', models.OneToOneField(help_text='id произведения, обязательное поле', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_title_id', to='reviews.titles')),
            ],
        ),
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Введите текст комментария, обязательное поле.', verbose_name='Текст комментария')),
                ('pub_date', models.DateField(auto_now=True, verbose_name='Дата')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('title_id', models.ForeignKey(help_text='id отзыва, обязательное поле.', on_delete=django.db.models.deletion.CASCADE, related_name='comments_titles_id', to='reviews.reviews')),
            ],
        ),
    ]
