# Generated by Django 3.2 on 2023-06-15 11:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genres',
            name='titles',
            field=models.ManyToManyField(help_text='Выберите фильмы для жанра', related_name='genres_titles', to='reviews.Titles', verbose_name='Фильмы'),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='title_id',
            field=models.ForeignKey(help_text='id произведения, обязательное поле', on_delete=django.db.models.deletion.CASCADE, related_name='reviews_title_id', to='reviews.titles'),
        ),
        migrations.AlterField(
            model_name='titles',
            name='category',
            field=models.ForeignKey(help_text='Введите категорию произведения, поле обязательное', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='reviews.categories', verbose_name='Категория'),
        ),
        migrations.RemoveField(
            model_name='titles',
            name='genre',
        ),
        migrations.AddField(
            model_name='titles',
            name='genre',
            field=models.ManyToManyField(help_text='Введите жанр произведения, поле обязательное', related_name='genres', to='reviews.Genres', verbose_name='Жанр'),
        ),
    ]
