# Generated by Django 3.2 on 2023-06-24 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='reviews_id',
            field=models.ForeignKey(help_text='id отзыва, обязательное поле.', on_delete=django.db.models.deletion.CASCADE, related_name='comment_Reviews', to='reviews.review'),
        ),
    ]
