# Generated by Django 3.2 on 2023-06-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_auto_20230616_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titles',
            name='name',
            field=models.CharField(help_text='Введите название произведения, это поле обязательное', max_length=256, unique=True, verbose_name='Название произведения'),
        ),
    ]
